### ISSUE TITLE
update 1.5.3 to CocoaPods 

### ISSUE THREAD

**Issue by ferrerod** [kaandedeoglu/KDCircularProgress#102]
_Originally posted by @ryanfelton in https://github.com/kaandedeoglu/KDCircularProgress/pull/101#issuecomment-430603040_

@ryanfelton is correct. Currently, the CocoaPod Spec https://cocoapods.org/pods/KDCircularProgress/ points to KDCircularProgress 1.5.2 so trying to compile results in Swift compiler errors now, not just warnings.

**Comment by ryanfelton** [comment]
👍

**Comment by kaandedeoglu** [comment]
Sorry to all that has been waiting for the Cocoapods version upgrade, I had some problems with pod trunk push commands, I'll try to sort them out next week. Meanwhile you can always pull the master commit

```
pod 'KDCircularProgress', :branch => 'master'
```

**Comment by ryanfelton** [comment]
@kaandedeoglu An update on fixing the Cocoapods push to trunk? I would like to use the official release. Thanks!

**Comment by PAlkisP** [comment]
@kaandedeoglu Any news on this?

**Comment by Faydee1220** [comment]
Try this:
pod 'KDCircularProgress', :git => 'https://github.com/kaandedeoglu/KDCircularProgress.git', :branch => 'master'

**Comment by ferrerod** [comment]
The problem is that this approach won’t allow us to ‘pin’ the pod version to a particular tag/version. 
It would take less time to reply to the email vs just fixing it :-)

**Comment by libern** [comment]
Any updates?

**Comment by kaandedeoglu** [comment]
Released version 1.5.4 on Cocoapods that points to what is master at the moment

**Comment by ferrerod** [comment]
Not in front of my computer...

Does 1.5.4 point to a tag on git, or a specific commit, or “HEAD”? The phrase “what is master at the moment” is ambiguous.

**Comment by kaandedeoglu** [comment]
@ferrerod  It points to the 1.5.4 tag

**Comment by ferrerod** [comment]
+1
