### ISSUE TITLE
ObjC -  setColors / progressColors not found

### ISSUE THREAD

**Issue by tamir-maoz** [kaandedeoglu/KDCircularProgress#109]
Hi,
upgraded version from 1.5.2 to 1.5.4. i have a mix ObjC/Swift project  and i'm unable to set the progress colors from my ObjC classes.
getting the following error:
"Property 'progressColors' not found on object of type 'KDCircularProgress *'" 
also unable to use set(colors:) or any other function i found to set the progress colors.
am i missing anything ? 
how should i set the progress colors from my objC classes ?
Thanks.

**Comment by kaandedeoglu** [comment]
Hey,

I've just pushed an update, can you please `pod update` and try again?

**Comment by tamir-maoz** [comment]
Hi,
Thanks for the quick response.
two things:
1. I also noticed that "progress" property is also not found by objC classes
2. should i pull a specific branch? currently i'm pulling pod 'KDCircularProgress' and see no updates...

Thanks again.

**Comment by kaandedeoglu** [comment]
This was a hotfix so I just moved tags forward. You might need to downgrade to 1.5.2 `pod update` and then re-upgrade to 1.5.4 followed by a final `pod update`

**Comment by tamir-maoz** [comment]
Hi,
i have followed you suggestion but still same issues.
i think the problem is with set(colors: UIColor...) func.
it is the public version for set colors but UIColor... syntax is not supported by ObjC so the setter fails to get exposed to ObjC. 
Does it make sense? 

Thanks.

**Comment by kaandedeoglu** [comment]
You can directly set to `progressColors` property. Like:

```objc
self.p.progressColors = @[[UIColor greenColor], [UIColor blueColor]];
```

**Comment by tamir-maoz** [comment]
This is exactly how i use it, see image attached:
![Screen Shot 2019-04-28 at 18 19 39](https://user-images.githubusercontent.com/40631916/56866480-41dc6900-69e2-11e9-9a5b-49fbc6a71dcc.png)

**Comment by kaandedeoglu** [comment]
Interesting, I just started a new Objective-C project and everything works for me. I had to uninstall - reinstall as stated above after pushing the fix. Are you sure you did that step?

<img width="713" alt="image" src="https://user-images.githubusercontent.com/1566836/56866534-967be600-69da-11e9-80fb-46815e9c18ad.png">

**Comment by tamir-maoz** [comment]
Thanks for your support!
Well, i just looked at your last commit (488603e40685007b5fdbec6ea15c452512a3a2db) on github that added:
@objcMembers
to KDCircularProgress class.
however, i do not see that addition when i pull the repo via pods.
i tried:
force downgrade to 1.5.2 -> upgrade back to 1.5.4
remove KDCircularProgress from pod file -> re-adding KDCircularProgress to pod file

both resulted the same - no @objcMembers :(

**Comment by kaandedeoglu** [comment]
Okay, one more idea: please do `pod cache clean 'KDCircularProgress' --all` before doing the downgrade-upgrade dance

**Comment by tamir-maoz** [comment]
Hi @kaandedeoglu ,
I'm happy to say, clearing the pod cache did the trick! 
Your help is much appreciated, Thanks for the support.
