### ISSUE TITLE
App crashing when calling progress() from async thread

### ISSUE THREAD

**Issue by sneps85** [kaandedeoglu/KDCircularProgress#11]
My app is crashing when calling progress() and finished from async thread, as the progressLayer.presentationLayer() is nil.

Is that an issue of KDCircularProgress or am I doing something wrong?

**Comment by kaandedeoglu** [comment]
I've never had such issues, are you sure you're touching KDCircularProgress only on the main thread?

**Comment by sneps85** [comment]
I start Kdcircularprogress, then i make an Alamofire request. In the success callback i have to do some asyn calculation (dispatch_async) in a for loop, for which i am using thr kdcircularprogress. Therefore i call progress() inside this loop and finished() after the loop. But when i do not check if the progressLayer.presentationLayer() exists inside the progress() call before calling animateToAngle(), the app crashes.

**Comment by kaandedeoglu** [comment]
Okay I see.

To further understand the root of this, can I see a crash log and your sample code please?

**Comment by sneps85** [comment]
I updated the comment above. I do not have access to the code right know, i can give it to you on monday. But i think the description above explains the procedure quite good.

**Comment by sneps85** [comment]
Here a pseudocode:

Circularprogress.started()
Response Handler

Alamofire.request(.GET, "http://httpbin.org/get", parameters: ["foo": "bar"])
         .response { request, response, data, error in
            dispatch_async {
               for (index, row) in data {
                   Calc()
                   Circularprogress.progress(percentage: index/row.count)
                 }
                 Circularprogress.finished()
              }
          }

**Comment by kaandedeoglu** [comment]
here's the problem, you must switch back to the main thread before calling any of the CircularProgress' methods. 

```swift
    dispatch_async(dispatch_get_main_queue()) {
        Circularprogress.progress(...) // and so on
    }
```

**Comment by sneps85** [comment]
But how to do that? I get the percentage only in the async thread... Could you help me?

**Comment by sneps85** [comment]
for now, my workaround is to check if processLayer.presentationLayer() is not nil before calling animateToAngle() in progress()...

**Comment by sneps85** [comment]
No i have access to the code and i didn't remember, but inside of the progress(), finished() and started() methods, i do:

 dispatch_async(dispatch_get_main_queue()) {
         ...
}
