### ISSUE TITLE
Add Icon Image to the end of Progress Line?

### ISSUE THREAD

**Issue by nadimalam** [kaandedeoglu/KDCircularProgress#115]
Is this possible to do? 

I want to add a image to the end of the progress line, which follows the line animation around the circle when its making progress.

**Comment by kaandedeoglu** [comment]
I'm afraid this is not possible with the current version of KDCircularProgress. I believe to achieve this, you'd have to fork the library and modify the `draw(in ctx: CGContext)` method and/or place the image at the correct location while inspecting the `angle` property

**Comment by nadimalam** [comment]
> I'm afraid this is not possible with the current version of KDCircularProgress. I believe to achieve this, you'd have to fork the library and modify the `draw(in ctx: CGContext)` method and/or place the image at the correct location while inspecting the `angle` property

thank you for your response, just a question is on going support and updates now abandoned then for this framework or are you still working on it? Do you know of any alternative framework that can achieve this feature? 

thanks

**Comment by kaandedeoglu** [comment]
This library came out of my own needs while developing an app a while back. I think the features and usage has pretty much solidified, and I avoid doing anything that would break the API or backwards compatibility (a couple thousand apps still use it afaik). 

So nowadays it's mostly bug fixes with new iOS version when they arise.

That being said, I welcome PRs, given that they won't cause functionality changes for users who already have the library in production.

Putting an image at the tip of the progress line is a quite specific feature that doesn't justify adding new api in my opinion. However if you start working on it on a fork, I'm more than happy to take a look.

Thank you

**Comment by nadimalam** [comment]
Cool, thanks your reply, i understand mate. It was more for the future as that specific requirement i think could come up in an app im working on. I don't have the time now, but when i do need it then i will try fork a separate branch and work on this feature. Thanks!
