### ISSUE TITLE
Crashing when no width and height constraints set

### ISSUE THREAD

**Issue by sneps85** [kaandedeoglu/KDCircularProgress#12]
When no height and width constraint is set on the IB, but instead top,right,bottom,left constraints in combination with a aspect ratio constraint, the following code causes the crash:

let g = CGGradientCreateWithColorComponents(baseSpace, componentsArray, locations,componentsArray.count / 4)
                self.gradientCache = g
                gradient = g!

as g is nil.

Do i have to set height and width in the interface builder?

**Comment by kaandedeoglu** [comment]
Hello,

I just constructed a similar example in IB that seems to run just fine. Please construct an example project that crashes for me to look at. Please feel free to reopen this when you get a reproducible example.

Thank you :)

![screen shot 2015-10-07 at 4 28 27 pm](https://cloud.githubusercontent.com/assets/1566836/10338777/7f829748-6d10-11e5-9e9e-d96fd7403782.png)
