### ISSUE TITLE
圆环周围有锯齿 Circle surrounded by sawtooth

### ISSUE THREAD

**Issue by puyanLiu** [kaandedeoglu/KDCircularProgress#13]
您好，这个圆环周围发现有些锯齿，请问这个怎么解决，谢谢
Hello, found some sawtooth around the ring, could you tell me how to solve this，thanks

**Comment by kaandedeoglu** [comment]
hello, please post a screenshot

**Comment by kaandedeoglu** [comment]
closing this after no additional input after 1 week
