### ISSUE TITLE
Why progress animation speed decreases?

### ISSUE THREAD

**Issue by ArturSkachkov** [kaandedeoglu/KDCircularProgress#14]
After pressing the pause and re-activated every time the progress animation speed decreases. How to solve this problem?Thank you

**Comment by ArturSkachkov** [comment]
Using the method animateToAngle when you press a button and the activation of this method, the rate of progress is reduced. So precisely formulated

**Comment by kaandedeoglu** [comment]
You are right - the method takes duration and so the speed depends on the progress when the animation begins. I might consider adding an option to specify speed rather than duration, what do you think?

**Comment by ArturSkachkov** [comment]
Of course it would be convenient to specify the length of it, to re-start after the animation was completed simultaneously with the progress of the specified time. But if you simply turn on the parameters of speed, to be able to specify the speed at the first re-animation and after a pause as the same, or constant.Thank you so much for a great product.

**Comment by ArturSkachkov** [comment]
sorry for Google translator :)

**Comment by kaandedeoglu** [comment]
@ArturSkachkov I just pushed 1.3.1, the animate methods now have a relativeDuration parameter (defaults to `true`). If you set it to false, `KDCircularProgress` will treat the duration as the duration it would take to perform 1 full turn, and keep the speed constant independent from where the start angle is. closing the issue for now, you can reopen if it doesn't work for you.

**Comment by ArturSkachkov** [comment]
Thank you, it works!
