### ISSUE TITLE
animateFromAngle crashes

### ISSUE THREAD

**Issue by chienplee** [kaandedeoglu/KDCircularProgress#16]
Hi, 
First I would like to say thank you for creating this beautiful progress. I have a UICollectionView and inside my collectionviewCell I have predefined a KDCirularProgressView. However When I want to run the animation, the app crashes with the following message: 

The commented code is working fine, it is the animation that crashes the app.
Error message: fatal error: unexpectedly found nil while unwrapping an Optional value

Is this something that I did not code correctly or is there something I have missed? Thanks

![2016-01-25 1 13 55 pm](https://cloud.githubusercontent.com/assets/16417906/12543016/8bcf3d66-c365-11e5-9fa3-144d47675047.png)

![2016-01-25 1 10 56 pm](https://cloud.githubusercontent.com/assets/16417906/12542972/1fa74a7a-c365-11e5-86a3-63f0de0d62b3.png)

**Comment by kaandedeoglu** [comment]
@chienplee 
Hello,

Thanks for reporting this. I'll look into this later today and get back to you. I'm guessing the `presentationLayer()` returns `false` in some scenarios. I'll probably guard to make sure that `presentationLayer`. :thought_balloon:

**Comment by kaandedeoglu** [comment]
@chienplee Meanwhile a sample project demonstrating the crash would be amazing!

**Comment by kaandedeoglu** [comment]
@chienplee I've made the changes discussed, please `pod update` let me know.

**Comment by chienplee** [comment]
Hi,

My apology for the late reply. Yes the animation works fine now. I am amazed how you tackled this issue without a sample project, awesome job!

**Comment by orbsense** [comment]
I was running the previous version and ran into the same crashing bug.  I just updated to the build released a month or so ago and the bug went away!

Thank you so much for fixing this control, I LOVE it.  It has been a fantastic progress to show in my prototype application.

THANK YOU!
