### ISSUE TITLE
Setting start angle or angle cause bad access

### ISSUE THREAD

**Issue by DBL-Lee** [kaandedeoglu/KDCircularProgress#20]
Since the update, setting start angle or angle would crash and the error is bad access.

![screen shot 2016-04-09 at 21 01 46](https://cloud.githubusercontent.com/assets/8804410/14403777/a217d44a-fe96-11e5-8fc7-e18f1b2f4b08.png)

I can't figure out why changing from int to double implementation would cause this error?

If I use step over, the error occurs right after this line.

**Comment by kaandedeoglu** [comment]
this is very weird, the example project uses a very similar setup process without ever crashing. Few things come to mind:

- Can you please put a breakpoint before the crashing line and do `po roundIndicator.progressLayer` in the debugger and tell me what comes up. I'm assuming the progressLayer comes out as nil, considering that is the only other property that the setter for `startAngle` touches.

- Can you try initializing the progress view as a `let` local variable and only set it equal to the `roundIndicator` property at the end.

**Comment by DBL-Lee** [comment]
I am using cocoapods how should I see the private layer property in debugger?

I have tried the second suggestion but it still crashes.

**Comment by DBL-Lee** [comment]
I copied the file to my project. Then the problem went away (not even changing layer to public and outputing). I reinstalled the pods but it still crashes when using pod. Any idea why?

**Comment by kaandedeoglu** [comment]
Not really, I'm using it with Cocoapods in a project of mine as well, all works fine here.

**Comment by DBL-Lee** [comment]
Ok. I will just use the file itself in my project for the time being. Thank you very much!

**Comment by kaandedeoglu** [comment]
Closing this for the time being since nobody else apparently had this problem. please feel free to reopen if it persists or you get a better idea of what's going on 😄
