### ISSUE TITLE
How to remove the margin

### ISSUE THREAD

**Issue by klwoon** [kaandedeoglu/KDCircularProgress#21]
![screen shot 2016-04-11 at 6 16 33 pm](https://cloud.githubusercontent.com/assets/9354867/14424105/e054ad1a-0011-11e6-87fb-50eee035afd6.png)

May I ask how to remove the margin between the circle and the border (blue line of the square)?
Thanks

**Comment by klwoon** [comment]
![screen shot 2016-04-11 at 6 31 51 pm](https://cloud.githubusercontent.com/assets/9354867/14424452/b3fbc0f8-0013-11e6-84c5-e287c87d4cac.png)
Currently I'm fixing the height, and adjust the aspect ratio so that the circle touches the border. Please let me know if there's any better method.
Thanks.

**Comment by kaandedeoglu** [comment]
I'm afraid there's always going to be some padding. It's added to make sure that glows don't get clipped. In the future, I might consider removing the padding when the `.NoGlow` is set for the `glowMode` property.

**Comment by klwoon** [comment]
Thanks! Much appreciated!
