### ISSUE TITLE
complete circular when i scroll or get out of the view

### ISSUE THREAD

**Issue by ahmedsafadii** [kaandedeoglu/KDCircularProgress#25]
complete circular when i scroll or get out of the view

**Comment by kaandedeoglu** [comment]
can you please explain this better?

**Comment by ahmedsafadii** [comment]
try to use it inside cell in tableview , when you scroll down the circular get fill 

also if you leave the page and then back to it , same

**Comment by kaandedeoglu** [comment]
it sounds like this is a scenario that should be handled by you in `cellWillDisplay`, `cellDidEndDisplaying` delegate methods, not `KDCircularProgress`.
