### ISSUE TITLE
Progress size

### ISSUE THREAD

**Issue by alexsanderkhitev** [kaandedeoglu/KDCircularProgress#27]
Hello! Thank you for your framework. I have a trouble with it. I made frame for KDCircularProgress, but progress does not stretch to margins of its view. How can I make it? KDCircularProgress background color is black for example. Please help me.

https://monosnap.com/file/Xr6HE46g3AzzD5Q81d5kyet7h6LiE7

**Comment by kaandedeoglu** [comment]
@alexsanderkhitev Unfortunately this is a design decision made for this control. We always leave a `20%` padding to accommodate for the glows which extend the track area. I might consider removing this and use `clipsToBounds = false` as default but I'm afraid that will break sizing for a lot of existing users.

**Comment by alexsanderkhitev** [comment]
@kaandedeoglu thank you so much for your answer!
