### ISSUE TITLE
Color Transition issue

### ISSUE THREAD

**Issue by saiidabs** [kaandedeoglu/KDCircularProgress#38]
i want the circle to start of red and transition to yellow then finally to a complete green when it hits 360 degrees . With your libary the color would just transition back , how do i stop this? i want it to be like in the image bellow 
![goalbar](https://cloud.githubusercontent.com/assets/10105522/17843422/16ebd9a8-6871-11e6-931e-5ce887c4ea06.png)

**Comment by kaandedeoglu** [comment]
@saiidabs I'm afraid that's not possible considering how the library works at the moment. I'll try to make it work for a future version if I find the time :-)

**Comment by jvanakker** [comment]
+1 request for featuring a true circular gradient
