### ISSUE TITLE
Make usable in Storyboard?

### ISSUE THREAD

**Issue by andrewcbancroft** [kaandedeoglu/KDCircularProgress#4]
Hi!

Your circular progress bar has helped me immensely - thank you for creating it!

In a project I'm coding on, I tweaked the KDCircularProgress class to implement init(coder:) so that I could position the circular progress view with Auto Layout (rather than trying to mess with the positioning in code).  

Would you be interested in collaborating on the implementation of this init method?  I'm happy to create a pull request with what I've done so far... It works in the project I'm working on, so I think it might be a good start.  I'd definitely want it to be done in a way that you'd approve of though.  Let me know what you think!

Andrew

**Comment by kaandedeoglu** [comment]
Hi,

I've been meaning to implement init?(coder aDecoder: NSCoder) for sometime but I've been extremely busy over the last couple of months and did not have much time for it. I'd like to see your implementation, please send a pull request and we'll go from there. Oh also thank you for contributing

Kaan

**Comment by andrewcbancroft** [comment]
My pleasure, Kaan!  I'll make it my goal to send you an implementation this evening.
