### ISSUE TITLE
IBDesignable support stops working when installed via Carthage

### ISSUE THREAD

**Issue by kaandedeoglu** [kaandedeoglu/KDCircularProgress#45]
I don't know why it wouldn't work. I would welcome any suggestions or help.

**Comment by pedromancheno** [comment]
There's a workaround apparently, where you subclass the view in your own project and make that a designable. But that would requiere the view to be marked as `open` instead of `public`

**Comment by kaandedeoglu** [comment]
@pedromancheno Thank you, after running some tests, I can confirm that the proposed solution works but requires too much (considering how many @IBInspectable properties `KDProgressView` has) boilerplate by the end user. 

Therefore I've decided to keep everything as is and hope that Apple fixes this at some point. And if interface builder support is important, one can always choose to install `KDCircularProgress` manually or with Cocoapods, which happens to live in a single file. Thank you again for the help 😀
