### ISSUE TITLE
animateDidStop calls animationcompletionblock before end of animation

### ISSUE THREAD

**Issue by Neogene** [kaandedeoglu/KDCircularProgress#47]
Hi,

animationDidStop calls animationcompletionblock when started (iOS 10)

To fix it had to add a where (now in swif3 syntax is changed) clause to the if to check if the "finished flag" is true :

if let completionBlock = animationCompletionBlock, flag == true {
  //animationCompletionBlock = nil
  //completionBlock(flag)
}

btw: really nice lib

**Comment by kaandedeoglu** [comment]
@Neogene The `animationCompletionBlock` has type `(Bool) -> Void`. The `Bool` argument passed with the block indicates if the animation ended on its own. If you start a new animation while another one is in motion, the completion block will still be called but with `false` as the passed argument. 

I think you should check on this `Bool` value when implementing your completion logic.

I hope it works for you and please let me know if something else is wrong and I've misunderstood your problem.
