### ISSUE TITLE
Interface Builder is not updating, together with IB Designables warnings

### ISSUE THREAD

**Issue by congthanh11a** [kaandedeoglu/KDCircularProgress#48]
Hello

On Xcode 8, I created a blank view and set the class to "KDCircularProgress". The parameter page was updated with parameters specific to KDCircularProgress, which is a great start. However, nothing shows up on Interface Builder (still a blank, white view). 

When I build the project, there was loads of warnings such as below.
Main.storyboard: warning: IB Designables: Ignoring user defined runtime attribute for key path "IBColor1" on instance of "UIView". Hit an exception when attempting to set its value: [<UIView 0x7fede05ed940> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key IBColor1.

Would you please suggest what might have gone wrong?

I use KDCircularProgress (1.5.0) from CocoaPod.

Many thanks.

**Comment by kaandedeoglu** [comment]
Hello,

I believe you should set `KDCircularProgress` to both Class and Module fields in the identity inspector in Interface Builder. That should fix it.

**Comment by congthanh11a** [comment]
Great, that works! Thank you very much!!
