### ISSUE TITLE
How to continue the animation from the same place after pause?

### ISSUE THREAD

**Issue by ArturSkachkov** [kaandedeoglu/KDCircularProgress#50]
Pressing continue after a pause the animation, the animation track starts from the beginning of the circle.
`progress.pauseAnimation() // PAUSE

// RESUME
progress.animate(fromAngle: 0, toAngle: 360, duration: duretionExersise) { completed in
                if completed {
                    print("RESUME")
                }
}`
how to fix to the track after a pause continued movement from the stopping point, not at starting position and continued to move at the same speed? Thank's

**Comment by MarkHendriks** [comment]
You should be able to use: progress.angle
progress.animate(progress.angle, toAngle: 360, duration: duretionExersise)

**Comment by MarkHendriks** [comment]
Try using: animateFromAngle
progress.animateFromAngle(progress.angle, toAngle: 360, duration: duretionExersise)

**Comment by ArturSkachkov** [comment]
Value of type 'KDCircularProgress' has no member 'animateFromAngle' !?

**Comment by ArturSkachkov** [comment]
it works
progress.animate(fromAngle: progress.angle, toAngle: 360, duration: duretionExersise)
