### ISSUE TITLE
Pod usage error

### ISSUE THREAD

**Issue by bonro001** [kaandedeoglu/KDCircularProgress#55]
Howdy,

Love the class but getting an error after I install using cocoa pods 1.1.1.  Here are my steps:

Add the pod to the pod file
pod install
add view to interface builder, with proper class and module
create outlet in associated source file

The last step is where it goes right off the rails, it does not find the class.  Importing does not solve the either.

Including a pic of the error and a pic of the pod installed.  Looking for a hint on why this is not working.

And, thanks in advance, great looking progress control!!!

![screen shot 2016-11-29 at 5 10 14 pm](https://cloud.githubusercontent.com/assets/803421/20733042/27a90a70-b657-11e6-8a76-4f7bc04ad01e.png)
![screen shot 2016-11-29 at 5 12 40 pm](https://cloud.githubusercontent.com/assets/803421/20733043/27bb886c-b657-11e6-8a5f-4d4742166109.png)

**Comment by bonro001** [comment]
Quick update, I got away from the pod and copied in the source, works great that way!  Followed this article: https://www.andrewcbancroft.com/2015/07/09/circular-progress-indicator-in-swift/

**Comment by kaandedeoglu** [comment]
@bonro001 I assume this is resolved. Closing this 👍
