### ISSUE TITLE
return progress bar to initial position

### ISSUE THREAD

**Issue by abara-kedavra** [kaandedeoglu/KDCircularProgress#56]
Hi, kaandedeoglu! Thank you for KDCircularProgress. Initially I have green progress bar. When I tap the button, green progress starts to disappear and black track appears. At finish I have only black track. If I tap the button again, green progress appears and starts to disappear again. I need to see green bar before I tap the button, right after the end of the animation. Is it possible to add something to "if completed { }" to return progress bar to initial position?

![screen shot 2016-12-08 at 20 27 14](https://cloud.githubusercontent.com/assets/14240337/21020282/e440e89a-bd84-11e6-8a73-9fd14048b4ee.png)
![screen shot 2016-12-08 at 20 27 55](https://cloud.githubusercontent.com/assets/14240337/21020286/e72236e0-bd84-11e6-85ca-b98dc85c33cc.png)

**Comment by kaandedeoglu** [comment]
maybe you can try to set the angle to the correct value in the completion block if the completed argument is true.

**Comment by abara-kedavra** [comment]
I tried to add "self.progress.angle = " to "if completed", but it didn't work. When I add "progress.angle = " to other place after other action - it started to work. And it only works if I have this code in two places (both of this strings). It's strange, but it works. Thank you.

**Comment by philmodin** [comment]
I'm having an issue with the completion on animate. It returns false until I run animate again. Is this intended?
Expected it to run the completion after animating and returning true without having to rerun.
