### ISSUE TITLE
Empty Space surrounding the progress indicator within the UIView

### ISSUE THREAD

**Issue by RyanHop3** [kaandedeoglu/KDCircularProgress#59]
Hi, I have noticed that when the KDCircularProgress UIView is implemented there is a lot of empty space within the UIView surrounding the indicator, which takes up a fair amount of screen real-estate(see attached photo). Is there a way to reduce the amount of empty space?
![kdprogress_example](https://cloud.githubusercontent.com/assets/19892764/21612959/1c7203b6-d1cb-11e6-8725-af453eb5f311.png)

**Comment by kaandedeoglu** [comment]
@RyanHop3 Hello,

This has come up before. `KDCircularProgress` always adds some padding to prevent clipping glows. There's a branch called `configurable radius` that you can check out that allows you to play with the padding. At some point (when I find the time & energy to invest in this rather big revamp) it will land in the master branch but will cause some breaking changes. Let me know if this helps you.

**Comment by RyanHop3** [comment]
Thanks for the reply. I'll have a look into it!

**Comment by n3o999** [comment]
Hi, now it's possible remove the padding around a View?

**Comment by SaezChristopher** [comment]
i hope you will merge it asap. I need it too

**Comment by SaezChristopher** [comment]
the branch is not up to date toward master. iremove the lib

**Comment by fukemy** [comment]
thanks, im gonna remove this lib
