### ISSUE TITLE
remove isUserInteractionEnabled = false 

### ISSUE THREAD

**Issue by iBicha** [kaandedeoglu/KDCircularProgress#60]
In my context, for further customization, i wanted to add a uibutton to the circular progress bar as a subview, and it drove me crazy because the button wouldn't work, only to find out later that `isUserInteractionEnabled = false` is set on `init`

the question is, does `isUserInteractionEnabled` affect the circular progress bar? (not as far as i know, please correct me if i'm wrong)

if that's the case, it should be removed, since it doesn't add any value to the component it self, only adds confusion in cases such as mine.

will make a PR as soon as i get the time (in case no one did)

**Comment by kaandedeoglu** [comment]
@iBicha Yes the `isUserInteractionEnabled = false` on init. 

This is a tradeoff with no clear winner to be honest. Imagine you add the circular progress on top of a `UIButton`, which would make it untappable. In any case, `isUserInteractionEnabled` is public so you are free to change it from within your application.

**Comment by iBicha** [comment]
right, but since it is set in the `init` it will override the property if it is set in the interface builder (which is why i spent quiet some time before i figured it out, because when i saw the isUserInteractionEnabled property checked in the interface builder, i assumed it will be the case in runtime)

I suggest removing it, (setting it to neither true or false) so that the default behaviour can take effect. I think that makes sense (in addition to it not adding any value to the component itself)
I hope i'm making sense

**Comment by kaandedeoglu** [comment]
That makes perfect sense! Send a PR if you'd like and I'll merge it 😊
