### ISSUE TITLE
Heavy flickering on iPad Air

### ISSUE THREAD

**Issue by variiance** [kaandedeoglu/KDCircularProgress#62]
Hi,

I am experiencing heavy flickering while testing the progress bar on an iPad Air.
UIView size is 600x600, using iOS 10.2.
I have also tested on an iPhone 5s, where the progress bar works fine, no issues on simulators either.
Unfortunately I am not allowed to upload a video, so I am attaching screenshots.
The progress bar seems to disappear and reappear rapidly, while the track stays put.

![screen shot 2017-01-16 at 11 48 28](https://cloud.githubusercontent.com/assets/7034859/21980095/2052e1fa-dbe2-11e6-97a4-30c02e36123d.jpg)
![screen shot 2017-01-16 at 11 48 15](https://cloud.githubusercontent.com/assets/7034859/21980102/2768897c-dbe2-11e6-95a8-473f6387ac8d.jpg)
![screen shot 2017-01-16 at 11 49 13](https://cloud.githubusercontent.com/assets/7034859/21980105/2b5ab01e-dbe2-11e6-911b-f1a50065a022.jpg)

**Comment by kaandedeoglu** [comment]
Is that a `UIVisualEffectView` on the background?

**Comment by variiance** [comment]
No, the background is a static image stored in assets, using a UIImageView.
All views are siblings.

**Comment by kaandedeoglu** [comment]
I can't really reproduce the issue since I don't own an iPad Air. I'll try to create a 600x600 progress on the iPhone and see if the problem occurs. 

Meanwhile, you can check if you can reproduce the issue in a new project that has no app logic but only the progress view.

**Comment by variiance** [comment]
I couldn't reproduce the issue on a clean project. I will take another look at the code in the original one.
