### ISSUE TITLE
Gradient along the circle

### ISSUE THREAD

**Issue by sibek** [kaandedeoglu/KDCircularProgress#63]
I want to use just two colors and show linear gradient along the circle like on this picture:
https://raw.githubusercontent.com/kaandedeoglu/KDCircularProgress/master/Assets/screenshot3.jpg

How can I do that please?

**Comment by kaandedeoglu** [comment]
```swift
progress.set(colors: UIColor.white, UIColor.orange)
```

should do the trick!

**Comment by sibek** [comment]
It's working for static image, but if I want to animate the progress it looks like the gradient is rotating. Imagine progress with white color for 0% and red for 100%. What I'm looking for is to see flawless gradient from white to red where white is always in 0% and full red in 100%. 

Like this:
![circlegradient](https://cloud.githubusercontent.com/assets/19273718/22287980/436fd408-e2f5-11e6-98ff-0c42edf72ee5.png)

**Comment by kaandedeoglu** [comment]
I'm afraid this will not work - see #38 

If you want to stop the gradient from rotating, try setting `gradientRotateSpeed` to 0.

**Comment by sibek** [comment]
I see. Thanks anyway for your effort.

**Comment by iamsanketray123** [comment]
This would be a nice feature to have. I am sure this is a requirement for a lot of people.

**Comment by jvanakker** [comment]
+1 request for featuring a true circular gradient
