### ISSUE TITLE
Property cannot be marked @IBInspectable because its type cannot be represented in Objective-C

### ISSUE THREAD

**Issue by Jasperav** [kaandedeoglu/KDCircularProgress#78]
I am using the newest Swift version and the newest xCode version. I get that error at this function:

    @IBInspectable public var glowMode: KDCircularProgressGlowMode = .forward {
        didSet {
            progressLayer.glowMode = glowMode
        }
    }

Have you plannend a upgrade to swift 4?

**Comment by jyounus** [comment]
Same here, any updates?

**Comment by Jasperav** [comment]
I just removed that function hehe, it works now

**Comment by jyounus** [comment]
I found this fork with Swift 4 updates, so currently using this: https://github.com/BalloonInc/KDCircularProgress

**Comment by kaandedeoglu** [comment]
Just pushed a fix on master. Let me know.

**Comment by jyounus** [comment]
It compiles fine for me, and seems to function fine. :D

**Comment by fairs-222** [comment]
public var glowMode: KDCircularProgressGlowMode = .forward {
    didSet {
        progressLayer.glowMode = glowMode
    }
}

**Comment by perlasivakrishna** [comment]
I updated to master branch using version 1.5.2, But still im getting error. I can see that Enum is not exposed to obj-c
