### ISSUE TITLE
Modify progress / track thickness Int only

### ISSUE THREAD

**Issue by sandervanhooft** [kaandedeoglu/KDCircularProgress#8]
Hi,

I love the progress bar, playing around with it. I however seem to be unable to modify the thickness of the track and progress when working with the inspector in the Storyboard on a Double level, seems to be Int only. So the modifications are very coarse, not usable for production. The Inspector form field seems to not accept Doubles here. Any clue? Developing on Xcode 6.4 for iOS 8.4.

Kind regards,

Sander
![screenshot](https://cloud.githubusercontent.com/assets/7265703/9722094/55247bc2-55a7-11e5-8671-f269be7843bc.png)

PS. I used this tutorial: https://www.andrewcbancroft.com/2015/07/09/circular-progress-indicator-in-swift/

**Comment by sandervanhooft** [comment]
(Restarting Xcode does not solve this issue.)

**Comment by kaandedeoglu** [comment]
Hello Sander,
I totally see your point, and this has happened to me trying to add examples through interface builder. We can multiply everything by 10, not a hard thing to achieve. I'm only afraid of breaking code for people who are already using `KDCircularProgress`. I'll have to try and see I guess. Thank you for bringing this up!

**Comment by sandervanhooft** [comment]
No problem! I'll code it instead of using the interface builder. Suitable workaround for a minor issue :).

**Comment by kaandedeoglu** [comment]
Okay! I'm closing this for the time being, if anything changes, I'll reply to this thread and let you know. Have a good one!
