### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by Kianoosh76** [kaandedeoglu/KDCircularProgress#80]
Hi, I'v faced a problem since I upgraded my xcode.
When I try to build the project, this compile error is raised.

```
@IBInspectable public var glowMode: KDCircularProgressGlowMode = .forward {
    didSet {
        progressLayer.glowMode = glowMode
    }
}
```

Property cannot be marked `@IBInspectable` because its type cannot be represented in Objective-C

**Comment by kaandedeoglu** [comment]
This is fixed on `master`, which is updated for Swift 4.

**Comment by return1225** [comment]
Thanks! The same issue for me, and it was fixed with pulling the latest master branch and included it in my project.
However, I try to implement the swift sample code and return pure black circle only. 
Anything wrong for me?

**Comment by return1225** [comment]
Yeah...I think I'm so foolish forgetting to setup angles in the end. Anyway, it's work now.

**Comment by NallapatiMalleswari** [comment]
I am also facing the same problem like the gay  Kianoosh was faced.But i dont know how to solve the problem .can you help me

**Comment by return1225** [comment]
What I did is just git from master branch and add the main class to my project rather than cocoa pod which maybe didn’t sync the latest version yet.

**Comment by Kiplol** [comment]
Can confirm that the Cocoapods version of 1.5.2 still has @IBInspectable error.

**Comment by NallapatiMalleswari** [comment]
no , resolved .

**Comment by neetrath** [comment]
Using KDCircularProgress (1.5.2) with Swift 4.0 still error

**Comment by kaandedeoglu** [comment]
Sorry for the delay. I've had problems with pushing a new Cocoapods version up. So both Carthage & Cocoapods users must point to the `master` branch to get the `Swift 4` version.

**Comment by cjlarsen** [comment]
In your podfile use `pod 'KDCircularProgress', :git => 'https://github.com/kaandedeoglu/KDCircularProgress'` for the time being

**Comment by mikecbone** [comment]
Using Cocoapods I've changed my pod file from 1.5.2 to getting the master branch as 'cjlarsen' suggests, and I've gone from the one initial error as described in this thread, to 12 saying "xxx is ambiguous for type lookup in this context"

**Comment by x-hovo-x** [comment]
Still same issue for me 1.5.2 Swift4.1

**Comment by kaandedeoglu** [comment]
Alright version 1.5.4 released on Cocoapods. Closing this one.. 

Sorry for the incredible delay, was going through stuff 🎈
