### ISSUE TITLE
How to change progress color

### ISSUE THREAD

**Issue by NallapatiMalleswari** [kaandedeoglu/KDCircularProgress#83]

**Comment by kaandedeoglu** [comment]
changing the contents `colors` property should do the trick.

**Comment by NallapatiMalleswari** [comment]
progress.progressColors = [UIColor .orange]  by using this line  i can change the color ,but how to use RGB values ,can you help me.

**Comment by kaandedeoglu** [comment]
How about something like

```swift
progress.progressColors = [UIColor(red: 0.4, green: 0.7, blue: 0.3, alpha: 1.0)]
```

**Comment by NallapatiMalleswari** [comment]
I tried like that ,but not working
