### ISSUE TITLE
Not an issue, just a (gentle) question

### ISSUE THREAD

**Issue by githubhero** [kaandedeoglu/KDCircularProgress#86]
Hi, I'm trying to use your KDCircularProgress to do something I'm not sure KDCircularProgress can do (I could not do it, anyway).

I have a slider and my slider goes from -180 to 180.
The starting value of the slider is -180.

When the slider is -180, I want the entire progress track "absent".

When the slider is -90, I want 25% of the track (starting from 180 degrees and clockwise), 
when 0, 50%, 
when 90, 75%, 
when 180, 100%.

I really could not do it, I get weird behaviors. Any tip?

**Comment by kaandedeoglu** [comment]
Hey, did you try playing around with `startAngle` property. Like setting it to -180?

**Comment by githubhero** [comment]
Finally, I found a way. 

I set the UISlider minimum value at 0 (not -180) and its maximum value to 360 (not +180).

In XCode, I set Circular Progress Angle to 180 and Start angle to 90 (don't ask me why, but this way anything works fine).

Finally, I use some Swift computed property to do some basic math.   :-)

Thanks for your kind answer!
