### ISSUE TITLE
flatMap is deprecated

### ISSUE THREAD

**Issue by githubhero** [kaandedeoglu/KDCircularProgress#89]
Hello, after installing the latest XCode version (Version 9.3 (9E145), Swift 4.1), I got a warning in `KDCircularProgress.swift`:

> 'flatMap' is deprecated: Please use compactMap(_:) for the case where closure returns an opt

Can I safely replace `flatMap` with `compactMap`?

**Comment by kaandedeoglu** [comment]
Yes I think we should start using `compactMap`, do you mind opening a PR for it :-)

**Comment by TomMajor** [comment]
The warning is only in one place
checkAndSetIBColors()
Here is an explanation about the case
https://useyourloaf.com/blog/replacing-flatmap-with-compactmap/
I could sure make an PR, but I am not sure about the full intention for this code. Is it only to make sure that there is at least one color not nil? Would it maybe better to have default values for the IB colors so this check is not needed at all?
Thanks,

**Comment by imrabti** [comment]
@kaandedeoglu I also get this deprecated message on Swift 4.1, I saw that there is already a PR that fix this but still not merged. https://github.com/kaandedeoglu/KDCircularProgress/pull/95

**Comment by kaandedeoglu** [comment]
Just merged, thanks for the heads up 👍
