### ISSUE TITLE
Feature request: inner fill color

### ISSUE THREAD

**Issue by jefflopes** [kaandedeoglu/KDCircularProgress#9]
Can you please consider adding a setter for the fill color inside the circle? It would be helpful in creating effects like the one in the attached image. Thanks!

![screen568x568](https://cloud.githubusercontent.com/assets/54537/9753850/12d528f4-5690-11e5-8f2e-ef6850eb7b37.jpeg)

**Comment by kaandedeoglu** [comment]
Hello, I'm not sure I understand what you mean by fill color. You can just pass in a single color for the progressColor property and it will act as in the screenshot above. i.e `circularProgress.progressColors = [UIColor.orangeColor()]`

**Comment by jefflopes** [comment]
To get the overlap effect between the two circles I'd like to make the KDCircularProgress's background clearColor but the inner part of the circle opaque and the same color as the cell's background.

**Comment by kaandedeoglu** [comment]
Okay - I see what you're trying to accomplish. I'll try to add this in the next few days. Thanks for bringing this up!

**Comment by kaandedeoglu** [comment]
I've added a property called `progressInsideFillColor`, that should do the trick. I've pushed the changes only to the swift-2 branch. Given that Xcode 7 is released in 6 days, there's no point in adding this to master. Please let me know if something does not work.

**Comment by jefflopes** [comment]
Thanks! Swift 2.0 branch is perfect. That's what I'm using.

**Comment by jefflopes** [comment]
Just integrated. Looks great! Thanks again.
