### ISSUE TITLE
Error "represented in Objective C"

### ISSUE THREAD

**Issue by iVoGia** [kaandedeoglu/KDCircularProgress#93]
I pod this framework to my project.
After that, it was appear this errror "Property cannot be marked @IBInspectable because its type cannot be represented in Objective C"
In the function below:
@IBInspectable public var glowMode: KDCircularProgressGlowMode = .forward {
        didSet {
            progressLayer.glowMode = glowMode
        }
    }
So, I cannot build the project.
How to fix it?

**Comment by bbvch13531** [comment]
```
public var glowMode: KDCircularProgressGlowMode = .forward {
didSet {
progressLayer.glowMode = glowMode
}
}
```
I resolve this compile error in this way.
